import { Skin } from "../../common.slint";

export struct MenuItemData := {
  title: string,
  index: int,
  is-sub: bool,
  //icon: string,
}

export global MenuConstants := {
  property <length> menuitem-height: 20px;
}

export MenuItem := Rectangle {
  property <image> icon <=> i.source;
  property <string> name <=> t.text;
  property <bool> active;
  property <bool> is-sub;
  property <int> index;
  callback clicked <=> ma.clicked;

  background: active ? rgba(100%, 100%, 100%, 14%) : ma.has-hover ? rgba(100%, 100%, 100%, 9%) : transparent;
  ma := TouchArea {}
  HorizontalLayout {
    alignment: start;
    spacing: 6px;
    padding: 8px;
    padding-left: is-sub ? 30px : 10px;
    padding-right: 30px;
    i := Image {
      width: 14px;
      height: source.height * 1px;
    }
    t := Text {
      color: white;
      font-size: Skin.MediumFont;
    }
  }
}