import { Skin } from "../../common.slint";
import { MenuItem, MenuItemData } from "./menuitem.slint";

export MenuBar := Rectangle {
  background: Skin.menuBar;
  property <int> active: 0;
  property <[MenuItemData]> menu-items;
  width: 200px;

  VerticalLayout {
    padding-left: 0px;
    padding-top: 35px;
    padding-right: 0px;
    padding-bottom: 12px;
    spacing: 8px;
    VerticalLayout {
      padding-left: 50px;
      padding-top: 0px;
      padding-right: 50px;
      padding-bottom: 54px;

      Image {
        source: @image-url("images/main-icon.png");
        height: source.height * 1px;
      }
    }
    //###  In the original, the icon is derived from the name
    for entry[idx] in root.menu-items : MenuItem {
      name: entry.title;
      //icon: entry.icon;
      active: root.active == idx;
    }
    Rectangle {}
    MenuItem { name: "Logout"; icon: @image-url("images/logout.png"); }
  }
}
