
struct ButtonColors := {
    base: color,
    pressed: color,
    hovered: color,
}

export global Skin := {
  property <color> background: #222;
  property <color> disabled: #99acb0;
  property <color> accent: #3d5a73;
  property <color> highlight: #286b43;
  property <color> highlightDarker: #25633e;
  property <color> menuBar: #2F4659;

  property <length> DefaultFont: 12px;
  property <length> TinyFont: 9px;
  property <length> SmallFont: 10px;
  property <length> MediumFont: 13px;
  property <length> LargeFont: 20px;
  property <length> HugeFont: 27px;
  property <length> TitleFont: 10px;
}