
import { LoginScreen } from "screens/login.slint";
import { MainScreen } from "screens/main/main.slint";
import { MenuItemData } from "./screens/main/menuitem.slint";

MainWindow := Window {
  callback quit();
  callback login_clicked <=> login.login_clicked;
  callback logout_clicked <=> main.logout_clicked;
  callback menu_item_clicked <=> main.menu-item-clicked;

  property <int> selected-screen: 0;
  property menu-items <=> main.menu-items;
  property menu-active <=> main.menu-active;
  property menu-viewport-height <=> main.menu-viewport-height;

  title: "Maple for Plex";
  preferred-width: 1024px;
  preferred-height: 576px;

  login := LoginScreen {
    visible: root.selected-screen == 0;
  }

  main := MainScreen {
    visible: root.selected-screen == 1;
  }

  //default-font-family: "Noto Sans";
  //default-font-size: Skin.base-font-size;
}