
import { LoginScreen } from "screens/login.slint";
import { MainScreen } from "screens/main.slint";

MainWindow := Window {
  callback quit();
  callback login_clicked();
  property <int> selected-screen: 0;

  title: "Maple for Plex";
  width: 1024px;
  height: 576px;

  login := LoginScreen {
    visible: root.selected-screen == 0;
    login-clicked => {
      root.login_clicked()
    }
  }

  main := MainScreen {
    visible: root.selected-screen == 1;
  }

  //default-font-family: "Noto Sans";
  //default-font-size: DefaultStyle.base-font-size;
}