import { Skin } from "../common.slint";

export global Button := Rectangle {
  callback clicked <=> touch.clicked;
  property <string> text: "Button";
  property <bool> enabled: true;

  width: 192px;
  height: 48px;
  border-radius: 6px;
  clip: true;

  background: !enabled ? Skin.disabled
    : touch.pressed ? Skin.highlightDarker
    : touch.has-hover ? Skin.highlight
    : Skin.accent;

  Text {
    width: parent.width;
    height: parent.height;
    text: root.text;
    color: #ddd;
    font-size: 18px;
    vertical-alignment: center;
    horizontal-alignment: center;
  }

  touch := TouchArea { }

}